---
name: Get data from APIs

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
jobs:
  collect:
    runs-on: ubuntu-latest
    name: Collect data from APIs
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: python collect.py
